all:
	python encode_bitFlip.py 0
	python encode_bitFlip.py 1
	python encode_bitFlip.py 2
	python encode_bitFlip.py 3
	python encode_bitFlip.py 4
	python encode_bitFlip.py 5

clean:
	rm -rf img/*.png


